# Generated by Django 6.0.6 on 2026-07-01 13:15

import accounts.models.accounts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.accounts.get_avatar_path, verbose_name='Аватар'),
        ),
    ]
