# Generated by Django 6.0.6 on 2026-07-02 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_myuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='posts_count',
        ),
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
