# Generated by Django 6.0.6 on 2026-07-06 08:19

import accounts.models.accounts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_myuser_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='', upload_to=accounts.models.accounts.get_avatar_path, verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
