# Generated by Django 6.0.6 on 2026-07-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_comments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
    ]
