# Generated by Django 6.0.6 on 2026-07-28 13:32

import insta.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_remove_posts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=1, upload_to=insta.models.post.get_image_path, verbose_name='Картина'),
            preserve_default=False,
        ),
    ]
